<a href="https://colab.research.google.com/github/MeldaChen/practice/blob/main/%E8%B3%87%E6%96%99%E5%BA%AB%E4%BD%9C%E6%A5%AD_%E6%9C%83%E5%93%A1%E7%B3%BB%E7%B5%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pymysql
import prettytable
import IPython.display as dp

db = pymysql.connect(
  host = "0.tcp.jp.ngrok.io",
  user = "root",
  passwd = "0824",
  db = "2022-10-05",
  charset = "utf8",
  port = 13728
)

cur=db.cursor()


while True:
  print("(0) 離開程式\n(1) 顯示會員列表\n(2) 新增會員資料\n(3) 更新會員資料\n(4) 刪除會員資料")
  n = input("指令：")
  if n == '1':
    cur.execute("SELECT * FROM `member`")

    data=cur.fetchall()

    list_all = []
    for d in data:
        list_all.append([d[0], d[1], d[2], d[3]])


    p1 = prettytable.PrettyTable(["編號", "姓名", "生日", "地址"], encoding="utf-8")
    p1.align["姓名"] = 'l'
    p1.align["生日"] = 'l'
    p1.align["地址"] = 'l'
    for i in range(0,len(list_all),1):
      p1.add_row(list_all[i][0:4])
    print(p1)

  if n == '2':
    a = input("請輸入會員姓名：")
    b = input("請輸入會員生日：")
    c = input("請輸入會員地址：")

    cur.execute("INSERT INTO `member`(`name`, `birthday`, `address`) VALUES(%s, %s, %s)", [a, b, c])
    db.commit()

    dp.clear_output(True)


  if n == '3':
    cur.execute("SELECT * FROM `member`")

    data=cur.fetchall()

    list_all = []
    for d in data:
        list_all.append([d[0], d[1], d[2], d[3]])


    p1 = prettytable.PrettyTable(["編號", "姓名", "生日", "地址"], encoding="utf-8")
    p1.align["姓名"] = 'l'
    p1.align["生日"] = 'l'
    p1.align["地址"] = 'l'
    for i in range(0,len(list_all),1):
      p1.add_row(list_all[i][0:4])
    print(p1)

    d = input("請選擇你要修改的資料編號：")

    dp.clear_output(True)

    a = input("請輸入會員姓名：")
    b = input("請輸入會員生日：")
    c = input("請輸入會員地址：")
    
    cur.execute(f"UPDATE `member` SET `name`= '{a}', `birthday`= '{b}', `address`= '{c}' WHERE `id`= {d}")
    db.commit()

    dp.clear_output(True)


  if n == '4':
    cur.execute("SELECT * FROM `member`")

    data=cur.fetchall()

    list_all = []
    for d in data:
        list_all.append([d[0], d[1], d[2], d[3]])


    p1 = prettytable.PrettyTable(["編號", "姓名", "生日", "地址"], encoding="utf-8")
    p1.align["姓名"] = 'l'
    p1.align["生日"] = 'l'
    p1.align["地址"] = 'l'
    for i in range(0,len(list_all),1):
      p1.add_row(list_all[i][0:4])
    print(p1)

    a = input("請選擇你要刪除的資料編號：")

    dp.clear_output(True)

    cur.execute(f"DELETE FROM `member` WHERE `id`= {a}")
    db.commit()

  if n == "0":
    break
    cur.close()


db.close()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pymysql in /usr/local/lib/python3.7/dist-packages (1.0.2)

In [ ]:
import pymysql
import prettytable
import IPython.display as dp

db = pymysql.connect(
  host = "0.tcp.jp.ngrok.io",
  user = "root",
  passwd = "0824",
  db = "2022-10-05",
  charset = "utf8",
  port = 18896
)

cur=db.cursor()


while True:
  print("(0) 離開程式\n(1) 顯示會員列表\n(2) 新增會員資料\n(3) 更新會員資料\n(4) 刪除會員資料")
  n = input("指令：")
  if n == '1':
    cur.execute("SELECT * FROM `member`")

    data=cur.fetchall()

    list_all = []
    for d in data:
        list_all.append([d[0], d[1], d[2], d[3]])


    p1 = prettytable.PrettyTable(["編號", "姓名", "生日", "地址"], encoding="utf-8")
    p1.align["姓名"] = 'l'
    p1.align["生日"] = 'l'
    p1.align["地址"] = 'l'
    for i in range(0,len(list_all),1):
      p1.add_row(list_all[i][0:4])
    print(p1)

  if n == '2':
    a = input("請輸入會員姓名：")
    b = input("請輸入會員生日：")
    c = input("請輸入會員地址：")

    cur.execute("INSERT INTO `member`(`name`, `birthday`, `address`) VALUES(%s, %s, %s)", [a, b, c])
    db.commit()

    dp.clear_output(True)


  if n == '3':
    cur.execute("SELECT * FROM `member`")

    data=cur.fetchall()

    list_all = []
    for d in data:
        list_all.append([d[0], d[1], d[2], d[3]])


    p1 = prettytable.PrettyTable(["編號", "姓名", "生日", "地址"], encoding="utf-8")
    p1.align["姓名"] = 'l'
    p1.align["生日"] = 'l'
    p1.align["地址"] = 'l'
    for i in range(0,len(list_all),1):
      p1.add_row(list_all[i][0:4])
    print(p1)

    d = input("請選擇你要修改的資料編號：")

    dp.clear_output(True)

    a = input("請輸入會員姓名：")
    b = input("請輸入會員生日：")
    c = input("請輸入會員地址：")
    
    cur.execute(f"UPDATE `member` SET `name`= '{a}', `birthday`= '{b}', `address`= '{c}' WHERE `id`= {d}")
    db.commit()

    dp.clear_output(True)


  if n == '4':
    cur.execute("SELECT * FROM `member`")

    data=cur.fetchall()

    list_all = []
    for d in data:
        list_all.append([d[0], d[1], d[2], d[3]])


    p1 = prettytable.PrettyTable(["編號", "姓名", "生日", "地址"], encoding="utf-8")
    p1.align["姓名"] = 'l'
    p1.align["生日"] = 'l'
    p1.align["地址"] = 'l'
    for i in range(0,len(list_all),1):
      p1.add_row(list_all[i][0:4])
    print(p1)

    a = input("請選擇你要刪除的資料編號：")

    dp.clear_output(True)

    cur.execute(f"DELETE FROM `member` WHERE `id`= {a}")
    db.commit()

  if n == "0":
    break
    cur.close()


db.close()

(0) 離開程式
(1) 顯示會員列表
(2) 新增會員資料
(3) 更新會員資料
(4) 刪除會員資料
指令：1
+------+------------+------------+--------------+
| 編號 | 姓名       | 生日       | 地址         |
+------+------------+------------+--------------+
|  1   | 陳文在     | 1993-11-01 | 台北市中山區 |
|  2   | 蕭宇殷     | 1990-05-22 | 新北市板橋區 |
|  3   | 藍天晴     | 1997-02-10 | 桃園市中壢區 |
|  4   | 林致世     | 1992-10-10 | 新竹縣竹東鎮 |
|  5   | 呂來來     | 1997-03-01 | 新北市萬里區 |
|  10  | 蔡杉智     | 1993-07-05 | 台北市大安區 |
|  11  | 姚文武     | 1995-07-11 | 台北市北投區 |
|  12  | 關自如     | 1996-10-21 | 新北市永和區 |
|  20  | 周怡敏     | 1988-12-11 | 新北市三重區 |
|  21  | 白依依     | 1985-01-05 | 新北市新店區 |
|  22  | 鄭芷茵     | 1993-02-10 | 新北市林口區 |
|  24  | aaa        | 1999-09-09 | bbb          |
|  25  | ddd        | 2021-08-25 | eee          |
|  26  | ggg        | 2021-08-01 | hhh          |
|  27  | 333        | 2021-05-05 | 444          |
|  28  | ppp        | 2021-01-01 | qqq          |
|  30  | 羊羊熊勾錐 | 2009-01-01 | 220          |
+------+------------+------------+--------------+
(0) 離開程式
(1) 顯示會員列表
(2) 新增會員資料
(3) 更新會員資料
(4) 刪除會員資料
指令：0